---
- name: check installed repository
  command: dpkg -l zfsonlinux
  ignore_errors: True
  register: installed
  changed_when: False

- name: fetch repository package
  get_url: url=http://archive.zfsonlinux.org/debian/pool/main/z/zfsonlinux/zfsonlinux_2%7Ewheezy_all.deb 
           dest=/tmp/zfsonlinux.deb
  when: installed|failed

- name: install repository
  apt16: deb=/tmp/zfsonlinux.deb
  when: installed|failed
  sudo: True
  register: add_repo

- name: cleanup
  file: path=/tmp/zfsonlinux.deb state=absent

- name: install spl
  apt: pkg=spl update_cache={{add_repo|changed}}
  sudo: True

- name: install zfs
  apt: pkg=debian-zfs
  sudo: True

- name: ZFS_MOUNT='yes'
  lineinfile: dest=/etc/default/zfs regexp=^ZFS_MOUNT= line=ZFS_MOUNT=\'yes\' backup=yes
  sudo: True

- name: zfs-mount
  service: name=zfs-mount enabled=yes state=started
  sudo: True
