---
# mac, debian
- name: test key presence
  command: test -f ~/.ssh/id_rsa
  register: key_presence
  ignore_errors: True
  changed_when: False

- name: create key
  command: ssh-keygen -t rsa -b 2048 -N '' -f ~/.ssh/id_rsa
  when: key_presence|failed

- name: copy sshd_config
  copy: src=../files/sshd_config dest=/etc/ssh/sshd_config backup=yes
  sudo: True
  notify: restart sshd
  when: ansible_distribution == "Debian"
