#!/usr/bin/env bash

ansible_dir=`dirname $0`
tmp=`mktemp $ansible_dir/.ansible-role.XXXXXX`
target=$1
role=$2
shift
shift

cat <<EOS > $tmp
---
- hosts: $target
  roles:
    - "$role"
EOS

ansible-playbook $tmp "$@"
rm $tmp

