---
- hosts: server
  tasks:
    - include: initialize.yml

- hosts: server
  tasks:
    - authorized_key: user="{{ansible_user_id}}" key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
  roles:
    - system/zfs
    - system/firewall
    - system/systemd
    - system/ntp

    - tools/ssh
    - tools/git/github
    - tools/heroku
    - tools/vim
    - tools/zsh

    - fluentd

    - recorder/chinachu

    - web/nginx
    - elasticsearch

    - haskell

    - database/postgresql

