---
- name: install systemd
  apt: pkg={{item}}
  sudo: True
  with_items:
    - systemd
    - python-dbus

- name: change grub config
  lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX_DEFAULT= 
      line="GRUB_CMDLINE_LINUX_DEFAULT=\"quiet init=/bin/systemd\""
  register: grub_config
  sudo: True

- name: update grub
  command: update-grub
  sudo: True
  when: grub_config.changed

- include: ../../../../include/reboot.yml
  when: grub_config.changed

