---
- name: install systemd
  apt: pkg={{item}}
  sudo: True
  with_items:
    - systemd
    - python-dbus

- name: change grub config
  lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX_DEFAULT= 
      line="GRUB_CMDLINE_LINUX_DEFAULT=\"quiet init=/bin/systemd\""
  register: grub_config
  sudo: True

- name: update grub
  command: update-grub
  sudo: True
  when: grub_config.changed

- name: reboot
  command: reboot
  sudo: True
  when: grub_config.changed

- name: wait for the server to go down (reboot)
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped
  sudo: False
  when: grub_config.changed

- name: wait for the server to come up
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started
  sudo: False
  when: grub_config.changed


