---
# mac, debian
- name: get public key
  register: public_key
  command: cat ~/.ssh/id_rsa.pub
  changed_when: False

- name: include token
  include_vars: "{{token_file_path}}"

- name: create request
  set_fact:
    request_body: |
      {
        "title": "{{key_title}}",
        "key":   "{{public_key.stdout_lines[0]}}"
      }

- name: register public key
  register: result
  uri: >
      method=POST url=https://api.github.com/user/keys
      body='{{ request_body | to_nice_json }}'
      HEADER_Authorization="token {{github_api_token}}"
      status_code=201
  changed_when: result.status == 201
  failed_when: result.status  not in [201, 422]

