---
- name: install vim(Debian)
  apt:  pkg=vim {{update_apt}}
  sudo: True
  when: ansible_distribution == "Debian"

- name:  clone .vim
  git: repo=git@github.com:philopon/.vim.git update=no
       dest=~/.vim accept_hostkey=yes recursive=yes

- name: link .vimrc
  file: src=~/.vim/vimrc dest=~/.vimrc state=link

