---
- name: install postgresql
  apt: pkg={{item}} {{update_apt}}
  with_items:
    - postgresql-9.3
    - python-psycopg2
  when: ansible_distribution == "Debian"

- name: start postgresql
  service: name=postgresql enabled=yes state=started

- name: create user db
  sudo_user: postgres
  postgresql_db: name={{ansible_user_id}} encoding='UTF-8' lc_collate='ja_JP.UTF-8' lc_ctype='ja_JP.UTF-8'

- name: create user
  sudo_user: postgres
  postgresql_user: db={{ansible_user_id}} name={{ansible_user_id}} password={{ansible_user_id}} role_attr_flags=SUPERUSER
