---
- file: path={{item}} state=absent
  with_fileglob:
    - /usr/share/doc
    - /usr/src/vboxguest*
    - /usr/src/virtualbox-ose-guest*

- apt: pkg=linux-headers-3.2.0-4-amd64 state=absent

- command: 
    find /usr/share/locale/ -mindepth 1 -maxdepth 1 -type d ! \( -name ja -o -name en_US \) -exec rm -rf {} \;

- command: find /var/lib/doc -type f -exec rm -f {} \;
  ignore_errors: True
