---
# mac, debian

- name: install curl
  sudo: True
  apt: pkg=curl {{update_apt}}
  when: ansible_distribution == "Debian"

- name: test key presence
  command: test -f ~/.ssh/heroku
  register: key_presence
  ignore_errors: True
  changed_when: False

- name: create heroku key
  command: ssh-keygen -t rsa -b 2048 -N '' -f ~/.ssh/heroku
  when: key_presence|failed

- name: get public key
  register: public_key
  command: cat ~/.ssh/heroku.pub
  changed_when: False

- name: include token
  include_vars: "{{token_file_path}}"

- name: create request
  set_fact:
    request_body: |
      {
        "public_key":   "{{public_key.stdout_lines[0]}}"
      }

- name: heroku common query
  set_fact: 
    heroku_query: |
      curl -s https://api.heroku.com/account/keys
      -H 'Accept: application/vnd.heroku+json; version=3'
      -H 'Content-Type: application/json'
      -u '{{heroku_user_name}}:{{heroku_api_token}}'

- name: check public key
  register: check
  ignore_errors: True
  changed_when: False
  script: |
    ../check_key.py \"{{heroku_user_name}}\" \"{{heroku_api_token}}\" \"{{public_key.stdout_lines[0]}}\"

- name: register public key
  register: result
  command: |
    {{heroku_query}} -XPOST -w '%{http_code}'
    -d '{ "public_key": "{{public_key.stdout_lines[0]}}" }'
  failed_when:   result.stdout_lines[-1][0:3] != "201"
  ignore_errors: result.stdout_lines[-1][0:3] != "422"
  changed_when:  result.stdout_lines[-1][0:3] == "201"
  when: check|failed

