---
# mac, debian
- name: get public key
  register: public_key
  command: cat ~/.ssh/id_rsa.pub
  changed_when: False

- name: include token
  include_vars: "{{token_file_path}}"

- name: create query
  set_fact:
    request_body: { public_key: "{{public_key.stdout_lines[0]}}" }

    heroku_query: >
      url=https://api.heroku.com/account/keys
      HEADER_Accept='application/vnd.heroku+json; version=3'
      HEADER_Content-Type='application/json'
      HEADER_Authorization="Bearer {{heroku_api_token}}"

    key_exists: False

- name: get public keys
  register: public_keys
  uri: "{{heroku_query}}"

- name: check public key
  set_fact: { key_exists: True }
  with_items: public_keys.json
  when: item.public_key == "{{public_key.stdout_lines[0]}}"

- name: register public key
  uri: >
    {{heroku_query}} method=POST body='{{ request_body|to_nice_json }}' status_code=201
  when: not key_exists
  changed_when: True

