---
- name: enable ufw
  ufw: state=enabled policy=deny 

- name: copy rules to application.d
  copy: src={{item}} dest=/etc/ufw/applications.d/ backup=yes
  with_fileglob:
    - ../files/applications.d/*

- name: reject outgoing
  ufw: state=enabled policy=reject direction=outgoing

- name: allow ssh from Home
  ufw: rule=allow name=OpenSSH src={{ item }}
  with_items:
    - "{{home_ip}}/{{home_netmask}}"

- name: allow outgoing
  ufw: rule=allow direction=out name="{{item}}"
  with_items:
    - WWW Full
    - DNS
    - ftp Full
