---
- name: check cabal
  tags: cabal
  register: cabal_installed
  ignore_errors: True
  changed_when: False
  command:  which cabal

- include: install.yml
  tags: cabal
  when: cabal_installed|failed

