---
- name: check cabal
  tags: cabal
  register: cabal_installed
  ignore_errors: True
  changed_when: False
  command:  test -f {{cabal_prefix}}/bin/cabal

- include: install.yml
  tags: cabal
  when: cabal_installed|failed

