---
- name: install pycurl
  apt: pkg=python-pycurl {{update_apt}}

- name: add repository key
  apt_key: id="{{repo_id}}" url="{{repo_key_url}}"

- name: add deb line
  apt_repository: repo="{{repo_deb_line}}"
