---
- name: check ghc
  tags: ghc
  register: ghc_installed
  ignore_errors: True
  command:  which ghc

- include: ghc.yml
  tags: ghc
  when: ghc_installed|failed

- name: check cabal
  tags: cabal
  register: cabal_installed
  ignore_errors: True
  command:  which cabal

- include: cabal.yml
  tags: cabal
  when: cabal_installed|failed

