---
- name: link libgmp
  file: src=libgmp.so.10 dest=/usr/lib/x86_64-linux-gnu/libgmp.so state=link
  sudo: True
  when: ansible_distribution == "Debian"

- name: fetch ghc archive
  get_url: url={{ghc_url}} dest=/tmp/{{ghc_archive}} validate_certs=no

- name: get ghc output directory
  register: source
  script:   ../../tar_output.sh /tmp/{{ghc_archive}}

- name: unarchive ghc
  command: tar xf {{ghc_archive}} chdir=/tmp creates="{{source.stdout_lines[0]}}"

- name: ghc configure
  command: ./configure --prefix={{ghc_prefix}} chdir="/tmp/{{source.stdout_lines[0]}}" creates="settings"

- name: install ghc
  sudo: True
  command: make install chdir="/tmp/{{source.stdout_lines[0]}}"

- name: clean up ghc
  file: path=/tmp/{{item}} state=absent 
  with_items:
    - "{{source.stdout_lines[0]}}"
    - "{{ghc_archive}}"
