---
- name: check ghc
  tags: ghc
  register: ghc_installed
  ignore_errors: True
  changed_when: False
  command:  test -f {{ghc_prefix}}/bin/{{ghc_command}}

- include: install.yml
  tags: ghc
  when: ghc_installed|failed
